spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/linhavital}
    username: ${DB_USER:linhavital}
    password: ${DB_PASSWORD:linhavital}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}

firebase:
  enabled: ${FIREBASE_ENABLED:false}
