spring:
  datasource:
    url: jdbc:postgresql://147.15.70.81:5432/linhavital
    username: linhavital_user
    password: ProjetoExtensao_2026_AjNv_Lv#

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true